### ISSUE TITLE
Anchors for headers are not kept in url

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/website#116]
Very often, I want to link to a specific section in the docs, such as e.g. https://www.openhab.org/docs/installation/windows.html#connecting-to-the-openhab-console.

But when selecting this anchor, the browser directly changes its url to https://www.openhab.org/docs/installation/windows.html#starting-openhab-as-a-service (which is the section that has a menu entry on the left).

When I now copy&paste the url, I very often do not notice it and thus have the wrong url posted.

Is there any way to keep the anchor in the url in place for such cases?

**Comment by Confectrician** [comment]
This seems to be related to openhab/openhab-docs#750

**Comment by ghys** [comment]
Indeed that's because of the "active header links" feature https://v0.vuepress.vuejs.org/default-theme-config/#active-header-links which is enabled by default.

I said before I "kind of" like it but not anymore, the URL manipulation it's doing is not worth the small benefit and even a little buggy. It's also impossible to go back to the "anchor-free" URL even when scrolling to the top. So it leads to unwanted anchors when copy-pasting from the address bar.

I'd suggest we disable it. Wdyt?

**Comment by Confectrician** [comment]
>I'd suggest we disable it. Wdyt?

Yeas. I think this is the best solution for now.
Maybe we can give it a try again, when (and if) the related problem gets adressed from vuepress side some time.
