### ISSUE TITLE
Remove "actions" section from Addons Page

### ISSUE THREAD

**Issue by davidgraeff** [openhab/website#154]
I question if it makes sense to list the OH1 actions (https://www.openhab.org/addons/#action) on the Add-ons page ("Show legacy add-ons" is off). Some of the listed actions have a OH2 successor already like the for Kodi, MQTT, Astro, Homeatic, DSC, Harmany. Some are just rather strange like Weather, xLP.

Those listed ones should be removed in any way. What remains are notification services and protocols like XMPP, Mail, PushBullet, Pushover, Pushsafer, Prowl, Twitter. I wonder if the category can be renamed to use the word "Actions" for the new automation engines actions.

**Comment by ghys** [comment]
Terminology changes and deprecations would be better be discussed over at openhab-docs since this affects https://www.openhab.org/docs/configuration/actions.html and potentially other places.

To clarify, the "Show legacy addons" checkbox only removes v1 bindings which have a v2 replacement (that is, an add-on with the same name except no '1' suffix), there could be a deprecation flag for example in the YAML frontmatter of the page, there is none at the moment; this would likely be a subjective case-by-case decision anyway.
