### ISSUE TITLE
Openhab.org: Community-Link https://www.openhab.org/community/ doesn’t work

### ISSUE THREAD

**Issue by muenkel** [openhab/website#268]
The community Link [https://www.openhab.org/community/](https://www.openhab.org/community/), which is used in the top menu on the pages like [https://www.openhab.org/docs/](https://www.openhab.org/docs/), leads to an empty page. I’ve tested this in Firefox and also in Chromium on two Linux systems. The Url [https://community.openhab.org/](https://community.openhab.org/) is ok.

**Comment by happenpappen** [comment]
The same here when accessing the site via HTTPS, additionally the top menu on the startpage is "invisible" - when moving the mouse to where the texts "Download", "Documentation", "Add-ons" etc. should be you can see, that there is actually a link to the respective topic, but the text is rendered invisible... when accessing the site via HTTP (tested this only in Safari and Chrome, since Firefox insists on using HTTPS) or when using https://next.openhab.org everything looks and works fine.

**Comment by Confectrician** [comment]
Should be solved on the caching side meanwhile.
Please report if there are still problems and i will reopen.
