### ISSUE TITLE
Update demo.openhab.org to use openHAB 3.1.0

### ISSUE THREAD

**Issue by wborn** [openhab/website#302]
It would be nice if everyone can try the latest release on https://demo.openhab.org/ without even installing it. :slightly_smiling_face:

**Comment by kaikreuzer** [comment]
Good idea - just updated the demo server! (fyi @ghys)

**Comment by ghys** [comment]
Thanks! Also FYI, it is likely the service worker cached the UI's assets locally in users' browsers pretty hardly at the time of first access. There is no detection that there was an update (it can be done, but right now it's not working, should probably fix that), so returning users should go to Help & About > Purge Caches and Refresh (at the bottom) to see changes.

**Comment by ghys** [comment]
By the way, I just did a `openhab> openhab:users clearSessions demo` on the demo server, as the sessions keep accumulating (in the hundreds if not thousands), this will log out everyone but it's probably something we should do regularly. The "My Profile" page is barely functioning since it lists all active sessions.

**Comment by wborn** [comment]
Thanks for the update and cleanup! 👍
