### ISSUE TITLE
Differentiate between menu articles and headlines better

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/website#45]
Current state:

![grafik](https://user-images.githubusercontent.com/2870104/40618159-ebd3451e-6290-11e8-8489-6e9d2db68e38.png)

With further indention and reduced margin:

![grafik](https://user-images.githubusercontent.com/2870104/40618266-477fadb2-6291-11e8-9197-0cb854fffb94.png)

This is not my final suggestion but rather a sample for comparison. Imho headlines should be clearly distinguishable to article names

**Comment by kaikreuzer** [comment]
I like the suggestion. @ghys Wdyt?

**Comment by ghys** [comment]
No opinion tbh, I'm fine with either.
I tend to refrain from modifying the default theme too much if I can help it (except for specific designs and bugfixes) because it adds maintenance - though this one should be pretty benign.

Another option I would consider is to remove the insertion of the current page's headlines in the (already pretty busy) sidebar altogether and keep it fixed, this would make this issue obsolete and would take care of #116 too.

https://v0.vuepress.vuejs.org/default-theme-config/#nested-header-links > set `themeConfig.sidebarDepth` to 0.
