### ISSUE TITLE
Load Google Fonts from openhab.org instead of Google

### ISSUE THREAD

**Issue by MHerbst** [openhab/website#74]
As a result of the GDPR, there have been discussions, especially in Germany whether it is allowed to download fonts from Google without asking or informing the user before the fonts are loaded ...

In order to avoid any problems with the fonts, we could load the fonts from openhab.org. There is a nice tool on https://google-webfonts-helper.herokuapp.com/fonts that helps with downloading the necessary fonts files from Google Fonts.

I have tried it for my own website and it worked smoothly.

**Comment by Confectrician** [comment]
Definetely a must have to be on the safe side.

**Comment by ghys** [comment]
Actually already did it in https://github.com/openhab/website/pull/62/commits/827d3d0b8316ae2ddadcd261c67392df65ab3911 as part of #62 but reverted it in #69... The Google servers have a more aggressive caching strategy which makes the font not "flicker" when reloading the page or navigating away from/back to the SPA.

Didn't investigate but I think it's because Netlify has the `must-revalidate` option set by default. Might be solvable with https://www.netlify.com/docs/headers-and-basic-auth/#custom-headers

**Comment by ghys** [comment]
#75 seems to have done the trick. As mentioned I'll be completely solved after the v2.3/v2.2 sites are regenerated with #73 included.

**Comment by kaikreuzer** [comment]
Can this be closed now?

**Comment by MHerbst** [comment]
I have checked it and no fonts are loaded from Google.

**Comment by ghys** [comment]
No, the sites for 2.2 and 2.3 are still using them (and are on an old version of VuePress and don't have the Algolia search), I was planning to generate them again along with 2.4 when it's out.
